/**
 * Types & Enums for Milestone 1.1C Revenue Conversation Loop
 */

export const DECISION_STATES = {
  NEW_HANDOFF: "NEW_HANDOFF",
  ELIGIBILITY_CHECKED: "ELIGIBILITY_CHECKED",
  DECISION_PROCESSED: "DECISION_PROCESSED",
  MEETING_PROPOSED: "MEETING_PROPOSED",
  MEETING_SCHEDULED: "MEETING_SCHEDULED",
  CRM_SYNCED: "CRM_SYNCED",
  SUPPRESSED: "SUPPRESSED",
  DISQUALIFIED: "DISQUALIFIED"
};

export const NEXT_ACTIONS = {
  PROPOSE_TIME_SLOTS: "propose_time_slots",
  SEND_MEETING_LINK: "send_meeting_link",
  ASK_QUALIFICATION_QUESTION: "ask_qualification_question",
  MARK_NOT_READY: "mark_not_ready",
  SUPPRESS_CONTACT: "suppress_contact"
};

export const MEETING_STATUSES = {
  DRY_RUN: "DRY_RUN",
  BLOCKED_PENDING_OWNER_APPROVAL: "BLOCKED_PENDING_OWNER_APPROVAL",
  SCHEDULED_SANDBOX: "SCHEDULED_SANDBOX",
  SCHEDULED_LIVE: "SCHEDULED_LIVE",
  FAILED: "FAILED"
};
