/**
 * CRM type definitions for Milestone 1.1B
 */

/**
 * @typedef {'dry_run'|'hubspot'|'salesforce'} CrmProviderId
 * @typedef {'dry_run'|'sandbox'|'live'} CrmMode
 * @typedef {'UPSERT_CONTACT_OR_DEAL'|'UPSERT_LEAD'|'ATTACH_NOTE'} CrmOperation
 * @typedef {'DRY_RUN'|'WRITTEN_SANDBOX'|'WRITTEN_LIVE'|'BLOCKED_PENDING_OWNER_APPROVAL'|'FAILED_RETRYABLE'|'FAILED_FINAL'} CrmWriteStatus
 */

export const CRM_PROVIDERS = ["dry_run", "hubspot", "salesforce"];
export const CRM_MODES = ["dry_run", "sandbox", "live"];

export const CRM_WRITE_STATUS = {
  DRY_RUN: "DRY_RUN",
  WRITTEN_SANDBOX: "WRITTEN_SANDBOX",
  WRITTEN_LIVE: "WRITTEN_LIVE",
  BLOCKED_PENDING_OWNER_APPROVAL: "BLOCKED_PENDING_OWNER_APPROVAL",
  FAILED_RETRYABLE: "FAILED_RETRYABLE",
  FAILED_FINAL: "FAILED_FINAL",
};

export const SCORECARD_VERDICTS = [
  "CRM_PROVIDER_READY_DRY_RUN_ONLY",
  "CRM_PROVIDER_SANDBOX_WRITE_SUCCEEDED",
  "CRM_PROVIDER_LIVE_WRITE_SUCCEEDED",
  "CRM_PROVIDER_WRITE_BLOCKED_PENDING_OWNER_APPROVAL",
  "CRM_PROVIDER_CONFIG_MISSING",
  "CRM_PROVIDER_WRITE_FAILED_RETRYABLE",
  "CRM_PROVIDER_WRITE_FAILED_FINAL",
  "HOLD_FOR_DATA_QUALITY_REVIEW",
];
